//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 02:30:49 PM BST 
//


package com.cisco.schema.cisco_xmf.v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.cisco.com/schema/cisco_xmf/v1_0}enableMediaForking" minOccurs="0"/>
 *         &lt;element ref="{http://www.cisco.com/schema/cisco_xmf/v1_0}disableMediaForking" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "enableMediaForking",
    "disableMediaForking"
})
@XmlRootElement(name = "action")
public class Action {

    protected EnableMediaForking enableMediaForking;
    protected String disableMediaForking;

    /**
     * Gets the value of the enableMediaForking property.
     * 
     * @return
     *     possible object is
     *     {@link EnableMediaForking }
     *     
     */
    public EnableMediaForking getEnableMediaForking() {
        return enableMediaForking;
    }

    /**
     * Sets the value of the enableMediaForking property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnableMediaForking }
     *     
     */
    public void setEnableMediaForking(EnableMediaForking value) {
        this.enableMediaForking = value;
    }

    /**
     * Gets the value of the disableMediaForking property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisableMediaForking() {
        return disableMediaForking;
    }

    /**
     * Sets the value of the disableMediaForking property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisableMediaForking(String value) {
        this.disableMediaForking = value;
    }

}
