//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 02:30:49 PM BST 
//


package com.cisco.schema.cisco_xmf.v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.cisco.com/schema/cisco_xmf/v1_0}connData"/>
 *         &lt;element ref="{http://www.cisco.com/schema/cisco_xmf/v1_0}guid"/>
 *         &lt;element ref="{http://www.cisco.com/schema/cisco_xmf/v1_0}guidAltFormat"/>
 *         &lt;element ref="{http://www.cisco.com/schema/cisco_xmf/v1_0}callingAddrData"/>
 *         &lt;element ref="{http://www.cisco.com/schema/cisco_xmf/v1_0}calledAddrData"/>
 *         &lt;element ref="{http://www.cisco.com/schema/cisco_xmf/v1_0}connIntfType"/>
 *         &lt;element ref="{http://www.cisco.com/schema/cisco_xmf/v1_0}mediaData"/>
 *         &lt;element ref="{http://www.cisco.com/schema/cisco_xmf/v1_0}connIntf"/>
 *         &lt;element ref="{http://www.cisco.com/schema/cisco_xmf/v1_0}connDirectionType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "connData",
    "guid",
    "guidAltFormat",
    "callingAddrData",
    "calledAddrData",
    "connIntfType",
    "mediaData",
    "connIntf",
    "connDirectionType"
})
@XmlRootElement(name = "connDetailData")
public class ConnDetailData {

    @XmlElement(required = true)
    protected ConnData connData;
    @XmlElement(required = true)
    protected String guid;
    @XmlElement(required = true)
    protected String guidAltFormat;
    @XmlElement(required = true)
    protected CallingAddrData callingAddrData;
    @XmlElement(required = true)
    protected CalledAddrData calledAddrData;
    @XmlElement(required = true)
    protected String connIntfType;
    @XmlElement(required = true)
    protected MediaData mediaData;
    @XmlElement(required = true)
    protected String connIntf;
    @XmlElement(required = true)
    protected String connDirectionType;

    /**
     * Gets the value of the connData property.
     * 
     * @return
     *     possible object is
     *     {@link ConnData }
     *     
     */
    public ConnData getConnData() {
        return connData;
    }

    /**
     * Sets the value of the connData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConnData }
     *     
     */
    public void setConnData(ConnData value) {
        this.connData = value;
    }

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuid() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuid(String value) {
        this.guid = value;
    }

    /**
     * Gets the value of the guidAltFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuidAltFormat() {
        return guidAltFormat;
    }

    /**
     * Sets the value of the guidAltFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuidAltFormat(String value) {
        this.guidAltFormat = value;
    }

    /**
     * Gets the value of the callingAddrData property.
     * 
     * @return
     *     possible object is
     *     {@link CallingAddrData }
     *     
     */
    public CallingAddrData getCallingAddrData() {
        return callingAddrData;
    }

    /**
     * Sets the value of the callingAddrData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CallingAddrData }
     *     
     */
    public void setCallingAddrData(CallingAddrData value) {
        this.callingAddrData = value;
    }

    /**
     * Gets the value of the calledAddrData property.
     * 
     * @return
     *     possible object is
     *     {@link CalledAddrData }
     *     
     */
    public CalledAddrData getCalledAddrData() {
        return calledAddrData;
    }

    /**
     * Sets the value of the calledAddrData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalledAddrData }
     *     
     */
    public void setCalledAddrData(CalledAddrData value) {
        this.calledAddrData = value;
    }

    /**
     * Gets the value of the connIntfType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnIntfType() {
        return connIntfType;
    }

    /**
     * Sets the value of the connIntfType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnIntfType(String value) {
        this.connIntfType = value;
    }

    /**
     * Gets the value of the mediaData property.
     * 
     * @return
     *     possible object is
     *     {@link MediaData }
     *     
     */
    public MediaData getMediaData() {
        return mediaData;
    }

    /**
     * Sets the value of the mediaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaData }
     *     
     */
    public void setMediaData(MediaData value) {
        this.mediaData = value;
    }

    /**
     * Gets the value of the connIntf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnIntf() {
        return connIntf;
    }

    /**
     * Sets the value of the connIntf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnIntf(String value) {
        this.connIntf = value;
    }

    /**
     * Gets the value of the connDirectionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnDirectionType() {
        return connDirectionType;
    }

    /**
     * Sets the value of the connDirectionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnDirectionType(String value) {
        this.connDirectionType = value;
    }

}
