//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 02:30:49 PM BST 
//


package com.cisco.schema.cisco_xmf.v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.cisco.com/schema/cisco_xmf/v1_0}farEndAddr"/>
 *         &lt;element ref="{http://www.cisco.com/schema/cisco_xmf/v1_0}nearEndAddr"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "farEndAddr",
    "nearEndAddr"
})
@XmlRootElement(name = "enableMediaForking")
public class EnableMediaForking {

    @XmlElement(required = true)
    protected FarEndAddr farEndAddr;
    @XmlElement(required = true)
    protected NearEndAddr nearEndAddr;

    /**
     * Gets the value of the farEndAddr property.
     * 
     * @return
     *     possible object is
     *     {@link FarEndAddr }
     *     
     */
    public FarEndAddr getFarEndAddr() {
        return farEndAddr;
    }

    /**
     * Sets the value of the farEndAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link FarEndAddr }
     *     
     */
    public void setFarEndAddr(FarEndAddr value) {
        this.farEndAddr = value;
    }

    /**
     * Gets the value of the nearEndAddr property.
     * 
     * @return
     *     possible object is
     *     {@link NearEndAddr }
     *     
     */
    public NearEndAddr getNearEndAddr() {
        return nearEndAddr;
    }

    /**
     * Sets the value of the nearEndAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link NearEndAddr }
     *     
     */
    public void setNearEndAddr(NearEndAddr value) {
        this.nearEndAddr = value;
    }

}
