//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 02:30:49 PM BST 
//


package com.cisco.schema.cisco_xmf.v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.cisco.com/schema/cisco_xmf/v1_0}type"/>
 *         &lt;element ref="{http://www.cisco.com/schema/cisco_xmf/v1_0}coderType"/>
 *         &lt;element ref="{http://www.cisco.com/schema/cisco_xmf/v1_0}coderByte"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "type",
    "coderType",
    "coderByte"
})
@XmlRootElement(name = "mediaData")
public class MediaData {

    @XmlElement(required = true)
    protected String type;
    @XmlElement(required = true)
    protected String coderType;
    @XmlElement(required = true)
    protected String coderByte;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the coderType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoderType() {
        return coderType;
    }

    /**
     * Sets the value of the coderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoderType(String value) {
        this.coderType = value;
    }

    /**
     * Gets the value of the coderByte property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoderByte() {
        return coderByte;
    }

    /**
     * Sets the value of the coderByte property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoderByte(String value) {
        this.coderByte = value;
    }

}
