//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 02:30:49 PM BST 
//


package com.cisco.schema.cisco_xmf.v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.cisco.com/schema/cisco_xmf/v1_0}msgHeader"/>
 *         &lt;element ref="{http://www.cisco.com/schema/cisco_xmf/v1_0}callData"/>
 *         &lt;element ref="{http://www.cisco.com/schema/cisco_xmf/v1_0}connData"/>
 *         &lt;element ref="{http://www.cisco.com/schema/cisco_xmf/v1_0}event"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "msgHeader",
    "callData",
    "connData",
    "event"
})
@XmlRootElement(name = "NotifyXmfConnectionData")
public class NotifyXmfConnectionData {

    @XmlElement(required = true)
    protected MsgHeader msgHeader;
    @XmlElement(required = true)
    protected CallData callData;
    @XmlElement(required = true)
    protected ConnData connData;
    @XmlElement(required = true)
    protected Event event;

    /**
     * Gets the value of the msgHeader property.
     * 
     * @return
     *     possible object is
     *     {@link MsgHeader }
     *     
     */
    public MsgHeader getMsgHeader() {
        return msgHeader;
    }

    /**
     * Sets the value of the msgHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgHeader }
     *     
     */
    public void setMsgHeader(MsgHeader value) {
        this.msgHeader = value;
    }

    /**
     * Gets the value of the callData property.
     * 
     * @return
     *     possible object is
     *     {@link CallData }
     *     
     */
    public CallData getCallData() {
        return callData;
    }

    /**
     * Sets the value of the callData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CallData }
     *     
     */
    public void setCallData(CallData value) {
        this.callData = value;
    }

    /**
     * Gets the value of the connData property.
     * 
     * @return
     *     possible object is
     *     {@link ConnData }
     *     
     */
    public ConnData getConnData() {
        return connData;
    }

    /**
     * Sets the value of the connData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConnData }
     *     
     */
    public void setConnData(ConnData value) {
        this.connData = value;
    }

    /**
     * Gets the value of the event property.
     * 
     * @return
     *     possible object is
     *     {@link Event }
     *     
     */
    public Event getEvent() {
        return event;
    }

    /**
     * Sets the value of the event property.
     * 
     * @param value
     *     allowed object is
     *     {@link Event }
     *     
     */
    public void setEvent(Event value) {
        this.event = value;
    }

}
