//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 02:30:49 PM BST 
//


package com.cisco.schema.cisco_xmf.v1_0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cisco.schema.cisco_xmf.v1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MediaForkingState_QNAME = new QName("http://www.cisco.com/schema/cisco_xmf/v1_0", "mediaForkingState");
    private final static QName _CoderByte_QNAME = new QName("http://www.cisco.com/schema/cisco_xmf/v1_0", "coderByte");
    private final static QName _CallID_QNAME = new QName("http://www.cisco.com/schema/cisco_xmf/v1_0", "callID");
    private final static QName _ConnDirectionType_QNAME = new QName("http://www.cisco.com/schema/cisco_xmf/v1_0", "connDirectionType");
    private final static QName _CoderType_QNAME = new QName("http://www.cisco.com/schema/cisco_xmf/v1_0", "coderType");
    private final static QName _Url_QNAME = new QName("http://www.cisco.com/schema/cisco_xmf/v1_0", "url");
    private final static QName _TransactionID_QNAME = new QName("http://www.cisco.com/schema/cisco_xmf/v1_0", "transactionID");
    private final static QName _ConnIntf_QNAME = new QName("http://www.cisco.com/schema/cisco_xmf/v1_0", "connIntf");
    private final static QName _Type_QNAME = new QName("http://www.cisco.com/schema/cisco_xmf/v1_0", "type");
    private final static QName _GuidAltFormat_QNAME = new QName("http://www.cisco.com/schema/cisco_xmf/v1_0", "guidAltFormat");
    private final static QName _ConnectionEventsFilter_QNAME = new QName("http://www.cisco.com/schema/cisco_xmf/v1_0", "connectionEventsFilter");
    private final static QName _DisableMediaForking_QNAME = new QName("http://www.cisco.com/schema/cisco_xmf/v1_0", "disableMediaForking");
    private final static QName _MediaEventsFilter_QNAME = new QName("http://www.cisco.com/schema/cisco_xmf/v1_0", "mediaEventsFilter");
    private final static QName _Port_QNAME = new QName("http://www.cisco.com/schema/cisco_xmf/v1_0", "port");
    private final static QName _Ipv4_QNAME = new QName("http://www.cisco.com/schema/cisco_xmf/v1_0", "ipv4");
    private final static QName _ConnIntfType_QNAME = new QName("http://www.cisco.com/schema/cisco_xmf/v1_0", "connIntfType");
    private final static QName _ProviderStatus_QNAME = new QName("http://www.cisco.com/schema/cisco_xmf/v1_0", "providerStatus");
    private final static QName _Addr_QNAME = new QName("http://www.cisco.com/schema/cisco_xmf/v1_0", "addr");
    private final static QName _State_QNAME = new QName("http://www.cisco.com/schema/cisco_xmf/v1_0", "state");
    private final static QName _Guid_QNAME = new QName("http://www.cisco.com/schema/cisco_xmf/v1_0", "guid");
    private final static QName _Name_QNAME = new QName("http://www.cisco.com/schema/cisco_xmf/v1_0", "name");
    private final static QName _RegistrationID_QNAME = new QName("http://www.cisco.com/schema/cisco_xmf/v1_0", "registrationID");
    private final static QName _ConnID_QNAME = new QName("http://www.cisco.com/schema/cisco_xmf/v1_0", "connID");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cisco.schema.cisco_xmf.v1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProviderData }
     * 
     */
    public ProviderData createProviderData() {
        return new ProviderData();
    }

    /**
     * Create an instance of {@link CallData }
     * 
     */
    public CallData createCallData() {
        return new CallData();
    }

    /**
     * Create an instance of {@link RequestXmfRegister }
     * 
     */
    public RequestXmfRegister createRequestXmfRegister() {
        return new RequestXmfRegister();
    }

    /**
     * Create an instance of {@link ApplicationData }
     * 
     */
    public ApplicationData createApplicationData() {
        return new ApplicationData();
    }

    /**
     * Create an instance of {@link MsgHeader }
     * 
     */
    public MsgHeader createMsgHeader() {
        return new MsgHeader();
    }

    /**
     * Create an instance of {@link FarEndAddr }
     * 
     */
    public FarEndAddr createFarEndAddr() {
        return new FarEndAddr();
    }

    /**
     * Create an instance of {@link ConnDetailData }
     * 
     */
    public ConnDetailData createConnDetailData() {
        return new ConnDetailData();
    }

    /**
     * Create an instance of {@link ConnData }
     * 
     */
    public ConnData createConnData() {
        return new ConnData();
    }

    /**
     * Create an instance of {@link CallingAddrData }
     * 
     */
    public CallingAddrData createCallingAddrData() {
        return new CallingAddrData();
    }

    /**
     * Create an instance of {@link CalledAddrData }
     * 
     */
    public CalledAddrData createCalledAddrData() {
        return new CalledAddrData();
    }

    /**
     * Create an instance of {@link MediaData }
     * 
     */
    public MediaData createMediaData() {
        return new MediaData();
    }

    /**
     * Create an instance of {@link MediaForking }
     * 
     */
    public MediaForking createMediaForking() {
        return new MediaForking();
    }

    /**
     * Create an instance of {@link Action }
     * 
     */
    public Action createAction() {
        return new Action();
    }

    /**
     * Create an instance of {@link EnableMediaForking }
     * 
     */
    public EnableMediaForking createEnableMediaForking() {
        return new EnableMediaForking();
    }

    /**
     * Create an instance of {@link NearEndAddr }
     * 
     */
    public NearEndAddr createNearEndAddr() {
        return new NearEndAddr();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link Connected }
     * 
     */
    public Connected createConnected() {
        return new Connected();
    }

    /**
     * Create an instance of {@link ResponseXmfCallMediaForking }
     * 
     */
    public ResponseXmfCallMediaForking createResponseXmfCallMediaForking() {
        return new ResponseXmfCallMediaForking();
    }

    /**
     * Create an instance of {@link MediaEvent }
     * 
     */
    public MediaEvent createMediaEvent() {
        return new MediaEvent();
    }

    /**
     * Create an instance of {@link NotifyXmfConnectionData }
     * 
     */
    public NotifyXmfConnectionData createNotifyXmfConnectionData() {
        return new NotifyXmfConnectionData();
    }

    /**
     * Create an instance of {@link NotifyXmfCallData }
     * 
     */
    public NotifyXmfCallData createNotifyXmfCallData() {
        return new NotifyXmfCallData();
    }

    /**
     * Create an instance of {@link RequestXmfCallMediaForking }
     * 
     */
    public RequestXmfCallMediaForking createRequestXmfCallMediaForking() {
        return new RequestXmfCallMediaForking();
    }

    /**
     * Create an instance of {@link ResponseXmfRegister }
     * 
     */
    public ResponseXmfRegister createResponseXmfRegister() {
        return new ResponseXmfRegister();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cisco.com/schema/cisco_xmf/v1_0", name = "mediaForkingState")
    public JAXBElement<String> createMediaForkingState(String value) {
        return new JAXBElement<String>(_MediaForkingState_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cisco.com/schema/cisco_xmf/v1_0", name = "coderByte")
    public JAXBElement<String> createCoderByte(String value) {
        return new JAXBElement<String>(_CoderByte_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cisco.com/schema/cisco_xmf/v1_0", name = "callID")
    public JAXBElement<String> createCallID(String value) {
        return new JAXBElement<String>(_CallID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cisco.com/schema/cisco_xmf/v1_0", name = "connDirectionType")
    public JAXBElement<String> createConnDirectionType(String value) {
        return new JAXBElement<String>(_ConnDirectionType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cisco.com/schema/cisco_xmf/v1_0", name = "coderType")
    public JAXBElement<String> createCoderType(String value) {
        return new JAXBElement<String>(_CoderType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cisco.com/schema/cisco_xmf/v1_0", name = "url")
    public JAXBElement<String> createUrl(String value) {
        return new JAXBElement<String>(_Url_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cisco.com/schema/cisco_xmf/v1_0", name = "transactionID")
    public JAXBElement<String> createTransactionID(String value) {
        return new JAXBElement<String>(_TransactionID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cisco.com/schema/cisco_xmf/v1_0", name = "connIntf")
    public JAXBElement<String> createConnIntf(String value) {
        return new JAXBElement<String>(_ConnIntf_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cisco.com/schema/cisco_xmf/v1_0", name = "type")
    public JAXBElement<String> createType(String value) {
        return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cisco.com/schema/cisco_xmf/v1_0", name = "guidAltFormat")
    public JAXBElement<String> createGuidAltFormat(String value) {
        return new JAXBElement<String>(_GuidAltFormat_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cisco.com/schema/cisco_xmf/v1_0", name = "connectionEventsFilter")
    public JAXBElement<String> createConnectionEventsFilter(String value) {
        return new JAXBElement<String>(_ConnectionEventsFilter_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cisco.com/schema/cisco_xmf/v1_0", name = "disableMediaForking")
    public JAXBElement<String> createDisableMediaForking(String value) {
        return new JAXBElement<String>(_DisableMediaForking_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cisco.com/schema/cisco_xmf/v1_0", name = "mediaEventsFilter")
    public JAXBElement<String> createMediaEventsFilter(String value) {
        return new JAXBElement<String>(_MediaEventsFilter_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cisco.com/schema/cisco_xmf/v1_0", name = "port")
    public JAXBElement<String> createPort(String value) {
        return new JAXBElement<String>(_Port_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cisco.com/schema/cisco_xmf/v1_0", name = "ipv4")
    public JAXBElement<String> createIpv4(String value) {
        return new JAXBElement<String>(_Ipv4_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cisco.com/schema/cisco_xmf/v1_0", name = "connIntfType")
    public JAXBElement<String> createConnIntfType(String value) {
        return new JAXBElement<String>(_ConnIntfType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cisco.com/schema/cisco_xmf/v1_0", name = "providerStatus")
    public JAXBElement<String> createProviderStatus(String value) {
        return new JAXBElement<String>(_ProviderStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cisco.com/schema/cisco_xmf/v1_0", name = "addr")
    public JAXBElement<String> createAddr(String value) {
        return new JAXBElement<String>(_Addr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cisco.com/schema/cisco_xmf/v1_0", name = "state")
    public JAXBElement<String> createState(String value) {
        return new JAXBElement<String>(_State_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cisco.com/schema/cisco_xmf/v1_0", name = "guid")
    public JAXBElement<String> createGuid(String value) {
        return new JAXBElement<String>(_Guid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cisco.com/schema/cisco_xmf/v1_0", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cisco.com/schema/cisco_xmf/v1_0", name = "registrationID")
    public JAXBElement<String> createRegistrationID(String value) {
        return new JAXBElement<String>(_RegistrationID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cisco.com/schema/cisco_xmf/v1_0", name = "connID")
    public JAXBElement<String> createConnID(String value) {
        return new JAXBElement<String>(_ConnID_QNAME, String.class, null, value);
    }

}
