//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 02:30:49 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.cisco.com/schema/cisco_xmf/v1_0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.cisco.schema.cisco_xmf.v1_0;
