//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 02:30:49 PM BST 
//


package com.cisco.schema.cisco_xmf.v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.cisco.com/schema/cisco_xmf/v1_0}connDetailData"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "connDetailData"
})
@XmlRootElement(name = "connected")
public class Connected {

    @XmlElement(required = true)
    protected ConnDetailData connDetailData;

    /**
     * Gets the value of the connDetailData property.
     * 
     * @return
     *     possible object is
     *     {@link ConnDetailData }
     *     
     */
    public ConnDetailData getConnDetailData() {
        return connDetailData;
    }

    /**
     * Sets the value of the connDetailData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConnDetailData }
     *     
     */
    public void setConnDetailData(ConnDetailData value) {
        this.connDetailData = value;
    }

}
