//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 02:30:49 PM BST 
//


package com.cisco.schema.cisco_xmf.v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.cisco.com/schema/cisco_xmf/v1_0}msgHeader"/>
 *         &lt;element ref="{http://www.cisco.com/schema/cisco_xmf/v1_0}callData"/>
 *         &lt;element ref="{http://www.cisco.com/schema/cisco_xmf/v1_0}mediaEvent"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "msgHeader",
    "callData",
    "mediaEvent"
})
@XmlRootElement(name = "NotifyXmfCallData")
public class NotifyXmfCallData {

    @XmlElement(required = true)
    protected MsgHeader msgHeader;
    @XmlElement(required = true)
    protected CallData callData;
    @XmlElement(required = true)
    protected MediaEvent mediaEvent;

    /**
     * Gets the value of the msgHeader property.
     * 
     * @return
     *     possible object is
     *     {@link MsgHeader }
     *     
     */
    public MsgHeader getMsgHeader() {
        return msgHeader;
    }

    /**
     * Sets the value of the msgHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgHeader }
     *     
     */
    public void setMsgHeader(MsgHeader value) {
        this.msgHeader = value;
    }

    /**
     * Gets the value of the callData property.
     * 
     * @return
     *     possible object is
     *     {@link CallData }
     *     
     */
    public CallData getCallData() {
        return callData;
    }

    /**
     * Sets the value of the callData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CallData }
     *     
     */
    public void setCallData(CallData value) {
        this.callData = value;
    }

    /**
     * Gets the value of the mediaEvent property.
     * 
     * @return
     *     possible object is
     *     {@link MediaEvent }
     *     
     */
    public MediaEvent getMediaEvent() {
        return mediaEvent;
    }

    /**
     * Sets the value of the mediaEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaEvent }
     *     
     */
    public void setMediaEvent(MediaEvent value) {
        this.mediaEvent = value;
    }

}
