//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 02:30:49 PM BST 
//


package com.cisco.schema.cisco_xmf.v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.cisco.com/schema/cisco_xmf/v1_0}applicationData"/>
 *         &lt;element ref="{http://www.cisco.com/schema/cisco_xmf/v1_0}connectionEventsFilter"/>
 *         &lt;element ref="{http://www.cisco.com/schema/cisco_xmf/v1_0}mediaEventsFilter"/>
 *         &lt;element ref="{http://www.cisco.com/schema/cisco_xmf/v1_0}msgHeader"/>
 *         &lt;element ref="{http://www.cisco.com/schema/cisco_xmf/v1_0}providerData"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "applicationData",
    "connectionEventsFilter",
    "mediaEventsFilter",
    "msgHeader",
    "providerData"
})
@XmlRootElement(name = "RequestXmfRegister")
public class RequestXmfRegister {

    @XmlElement(required = true)
    protected ApplicationData applicationData;
    @XmlElement(required = true)
    protected String connectionEventsFilter;
    @XmlElement(required = true)
    protected String mediaEventsFilter;
    @XmlElement(required = true)
    protected MsgHeader msgHeader;
    @XmlElement(required = true)
    protected ProviderData providerData;

    /**
     * Gets the value of the applicationData property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationData }
     *     
     */
    public ApplicationData getApplicationData() {
        return applicationData;
    }

    /**
     * Sets the value of the applicationData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationData }
     *     
     */
    public void setApplicationData(ApplicationData value) {
        this.applicationData = value;
    }

    /**
     * Gets the value of the connectionEventsFilter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnectionEventsFilter() {
        return connectionEventsFilter;
    }

    /**
     * Sets the value of the connectionEventsFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnectionEventsFilter(String value) {
        this.connectionEventsFilter = value;
    }

    /**
     * Gets the value of the mediaEventsFilter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMediaEventsFilter() {
        return mediaEventsFilter;
    }

    /**
     * Sets the value of the mediaEventsFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMediaEventsFilter(String value) {
        this.mediaEventsFilter = value;
    }

    /**
     * Gets the value of the msgHeader property.
     * 
     * @return
     *     possible object is
     *     {@link MsgHeader }
     *     
     */
    public MsgHeader getMsgHeader() {
        return msgHeader;
    }

    /**
     * Sets the value of the msgHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgHeader }
     *     
     */
    public void setMsgHeader(MsgHeader value) {
        this.msgHeader = value;
    }

    /**
     * Gets the value of the providerData property.
     * 
     * @return
     *     possible object is
     *     {@link ProviderData }
     *     
     */
    public ProviderData getProviderData() {
        return providerData;
    }

    /**
     * Sets the value of the providerData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProviderData }
     *     
     */
    public void setProviderData(ProviderData value) {
        this.providerData = value;
    }

}
